Оптимизируй это (часть 1)
htmlacademy-react/990505-six-cities-14 pull request #11
Opened 2023-11-29 03:20 UTC by codefornia

2023-11-29 14:59 UTC, romien94 commented on src/pages/favorites/favorites.tsx
> +    <Page className={`page ${!offers.length && 'page--favorites-empty'}`} title="6 cities: favorites">
лучше тернарник используй, иначе у тебя false будет в классе ))

2023-11-29 14:59 UTC, romien94 commented on src/pages/favorites/favorites.tsx
> +      <main className={`page__main page__main--favorites ${!offers.length && 'page__main--favorites-empty'}`}>
то же самое

2023-11-29 15:00 UTC, romien94 commented on src/pages/login/login.tsx
> +                  pattern="(?=.*\d)(?=.*[A-z]).{2,}"
лучше вынести в константы сверху и передать сюда

2023-11-29 15:01 UTC, romien94 commented on src/pages/login/login.tsx
> +              <Link className="locations__item-link" to={AppRoute.Main} onClick={() => dispatch(setSelectedCityName(randomCity))}>
лучше для чтения вынести наверху и закрыть под useCallback

2023-11-29 15:02 UTC, romien94 commented on src/pages/main/main.tsx
> +  const getDefaultOrderSortedOffers = useCallback(() => offers.filter((item) => item.city.name === selectedCityName), [offers, selectedCityName]);
эм-с. может быть useMamo? чтобы массив уже получить, а не фильтровать вот так?

2023-11-29 15:02 UTC, romien94 commented on src/pages/main/sorting-form.tsx
> +        sortedOffers = [...sortedOffers].sort((a, b) => b.rating - a.rating);
лучше sortAt использовать

2023-11-29 15:03 UTC, romien94 commented on src/pages/offer/offer.tsx
> +                  {host.isPro && (<span className="offer__user-status">Pro</span>)}
можно без "("

2023-11-29 15:05 UTC, romien94 commented on src/pages/offer/reviews-form.tsx
> +    }).catch(() => setIsReviewSending(false));
мб setIsReviewSending(false) вынести в finally?

2023-11-29 15:07 UTC, romien94 commented on src/store/offers-data/offers-data.ts
> +      state.offers.map((item) => {
ента что такое? мы не мутируем состоянием таким образом. state.offers.map = state.offers.map(....)

2023-11-29 15:12 UTC, romien94 commented on src/store/user-process/user-process.ts
> +        state.authorizationStatus = action.payload === null ? AuthorizationStatus.NoAuth : AuthorizationStatus.Auth;
можно дубли вынести выше в отдельные функции для переиспользования

2023-11-29 15:13 UTC, romien94 requested changes
посмотри комменты, пожалуйста

2023-11-30 10:55 UTC, codefornia commented on src/pages/offer/reviews-form.tsx
> +    }).catch(() => setIsReviewSending(false));
Вернула finally. catch блок нужен чтобы хоть как-то "обработать" эксепшен.

2023-11-30 11:22 UTC, codefornia commented on src/pages/main/sorting-form.tsx
> +        sortedOffers = [...sortedOffers].sort((a, b) => b.rating - a.rating);
Такого метода нет. Есть сторонние библиотеки, но тут перебор на мой взгляд ради трёх сортировок.

2023-11-30 12:49 UTC, merged