Маршрут по тайным тропам
htmlacademy-react/990505-six-cities-14 pull request #3
Opened 2023-10-18 16:33 UTC by codefornia

add routes

2023-10-18 17:25 UTC, romien94 commented on src/components/app/app.tsx
> +import Offer from '../../pages/offer/offer';
чтобы дважды не дублировать offer/offer и т.д. лучше создавать это в index.ts, а папки внутри pages создавать с большой буквы Offer

2023-10-18 17:26 UTC, romien94 commented on src/components/app/app.tsx
> +import NotFoundPage from '../../pages/not-found-page/not-found-page';
в pages тоже можно создать index.ts и реэксортить там файлики
// index.ts
export { NotFoundPage } from './NotFoundPage';
и т.д..

2023-10-18 18:07 UTC, romien94 commented on src/components/app/header/header.tsx
>        <div className="container">
Контейнер лучше вынести в отдельный компонент для переиспользования

2023-10-18 18:08 UTC, romien94 commented on src/components/app/private-route.tsx
> +  const hasAccess = true;
лучше вынести на самый верх области видимости. то есть, на уровень файла

2023-10-18 18:09 UTC, romien94 commented on src/pages/favorites/favorites.tsx
>      <div className="page">
давай Page вынесем в отдельный компонент? У него внутри всегда будет лежать helmet, а в качестве пропса title он будет принимать то, что мы закинем внутрь helmet

2023-10-18 18:13 UTC, romien94 requested changes
в целом, всё в порядке. обрати внимание на комментарии - это нам поможет несколько упростить жизнь, уменьшить количество кода и сделать его немножечко лучше :)

2023-10-19 04:07 UTC, codefornia commented on src/components/app/app.tsx
> +import Offer from '../../pages/offer/offer';
именовала в соответсвии с критериямиБ21 и Б22

2023-10-19 05:24 UTC, codefornia commented on src/pages/favorites/favorites.tsx
>      <div className="page">
сделала.  + в Page вынесла Header. В пропсы Page передаю классы, title и isAuthorizedUser который влияет на отрисовку Header

2023-10-19 05:30 UTC, codefornia commented on src/components/app/private-route.tsx
> +  const hasAccess = true;
но он итак на уровне файла app в котором используется

2023-10-19 05:30 UTC, codefornia commented on src/components/app/app.tsx
> +import NotFoundPage from '../../pages/not-found-page/not-found-page';
сделала

2023-10-19 08:24 UTC, codefornia commented on src/components/app/header/header.tsx
>        <div className="container">
именно контейнер без содержимого? вынесла без содержимого

2023-10-19 08:47 UTC, romien94 commented on src/components/app/private-route.tsx
> +  const hasAccess = true;
я про переменую hasAccess

2023-10-20 03:31 UTC, codefornia commented on src/components/app/private-route.tsx
> +  const hasAccess = true;
вынесла все переменные статуса и соотве6тсвенно изменю это когда буду работать с авторизацией

2023-10-20 03:35 UTC, merged