Обратная сторона реальности
htmlacademy-react/990505-six-cities-14 pull request #4
Opened 2023-10-30 12:59 UTC by codefornia

2023-10-30 19:00 UTC, romien94 commented on package.json
> +    "moment": "^2.29.4",
лучше залочить :)

2023-10-30 19:01 UTC, romien94 commented on src/components/app/app.tsx
> +import {AuthorizationStatus} from '../../const';
у тебя сверху уже есть импорт из этой же папки

2023-10-30 19:01 UTC, romien94 commented on src/components/app/app.tsx
>  import {JSX} from 'react';
можно не указывать ))

2023-10-30 19:03 UTC, romien94 commented on src/components/app/private-route.tsx
>    children: JSX.Element;
ReactNode | ReactNode[]

2023-10-30 19:03 UTC, romien94 commented on src/components/app/private-route.tsx
> +function PrivateRoute({authorizationStatus = AuthorizationStatus.Auth, children, redirectTo}: PrivateRouteProps): JSX.Element {
ts понимает, что мы возвращаем jsx в файлах с разрешением tsx

2023-10-30 19:04 UTC, romien94 commented on src/types/review.ts
> +  user: {
описание типа пользователя лучше вынести наверх, а тут его использовать

2023-10-30 19:06 UTC, romien94 commented on src/pages/offer/reviews-form.tsx
> +            <Fragment key={score}>
мб, вынесем в отдельный компонент, чтобы улучшить читаемость и сократить количество кода тут?

2023-10-30 19:11 UTC, romien94 commented on src/pages/offer/offer.tsx
> +      return nearPlace;
можно просто []

2023-10-30 19:12 UTC, romien94 commented on src/pages/offer/offer.tsx
> +    offers.filter((item)=> {
не понял, зачем пушить в массив, если тут ты просто можешь вернуть новый из отфильтрованных значений

2023-10-30 19:14 UTC, romien94 commented on src/pages/favorites/favorites.tsx
> +      if (sortedOffers[item.city.name] === undefined) {
можно записать так

const cityOffers = sortedOffers[item.city.name] || [];

2023-10-30 19:15 UTC, romien94 commented on src/mocks/review.ts
> +    'id': 1,
у ключей здесь совершенной не нужен синтаксис литералов :)

2023-10-30 19:15 UTC, romien94 commented on src/const.ts
> +  '5': 'perfect',
синтаксис литералов здесь не нужен

2023-10-30 19:16 UTC, romien94 commented on src/components/places-cards/place-card.tsx
> +        <p className="place-card__type">{`${type[0].toUpperCase()}${type.slice(1)}`}</p>
мб, вынесем в утильку capitalize?

2023-10-30 19:18 UTC, romien94 commented on src/components/app/reviews.tsx
> +            <b className="reviews__text-amount">{reviews.length} character{reviews.length > 1 && 's'}</b>.
мб, в утильку вынесем преобразование ко множественному числу? ниже тоже видел похожее

2023-10-30 19:18 UTC, romien94 commented on src/components/app/reviews.tsx
> +          defaultValue=''
пройдись prettier-ом. где-то двойные скобочки, где-то одинарные. нехорошо так :/

2023-10-30 19:19 UTC, romien94 commented on src/components/app/reviews.tsx
> +          <input
кажется, всё это можно вынести в константы и промапить это, вместо того, чтобы ручками писать?

2023-10-30 19:20 UTC, romien94 requested changes
в целом, всё оки, но есть, что можно сделать лучше :3

2023-10-31 15:31 UTC, codefornia commented on src/pages/offer/offer.tsx
> +    offers.filter((item)=> {
Сделала код очевиднее - заменила filter на forEach. Сделано это так для того, чтобы избежать функции slice, т.к. мне нужно лишь 3 элемента и не хотелось бы формировать массив из, например, 100 ради того чтобы их обрезать.

2023-10-31 16:08 UTC, codefornia commented on src/components/app/reviews.tsx
> +          <input
исправлено

2023-10-31 16:49 UTC, codefornia commented on src/components/places-cards/place-card.tsx
> +        <p className="place-card__type">{`${type[0].toUpperCase()}${type.slice(1)}`}</p>
вынесла

2023-10-31 16:49 UTC, codefornia commented on src/components/app/reviews.tsx
> +            <b className="reviews__text-amount">{reviews.length} character{reviews.length > 1 && 's'}</b>.
вынесла

2023-10-31 16:52 UTC, merged